# Generated by Django 4.1.5 on 2023-01-26 02:23

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2223', '2022-2023'), ('2324', '2023-2024'), ('2425', '2024-2025'), ('2526', '2025-2026'), ('2627', '2026-2027')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('P1', 'Primary 1'), ('P1A', 'Primary 1A'), ('P1B', 'Primary 1B'), ('P2', 'Primary 2'), ('P2A', 'Primary 2A'), ('P2B', 'Primary 2B'), ('P3', 'Primary 3'), ('P3A', 'Primary 3A'), ('P3B', 'Primary 3B'), ('P4', 'Primary 4'), ('P4A', 'Primary 4A'), ('P4B', 'Primary 4B'), ('P5', 'Primary 5'), ('P5A', 'Primary 5A'), ('P5B', 'Primary 5B'), ('P6', 'Primary 6'), ('P6A', 'Primary 6A'), ('P6B', 'Primary 6B'), ('S1', 'Secondary 1'), ('S2', 'Secondary 2'), ('S3', 'Secondary 3'), ('S4', 'Secondary 4'), ('PU1', 'Pre-U 1'), ('PU2', 'Pre-U 2')], max_length=3)),
                ('form_teacher', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(max_length=300, upload_to=webapp.models.Rename.save)),
                ('photo2', models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save)),
                ('photo3', models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save)),
                ('encoding1', models.BinaryField(blank=True, null=True)),
                ('encoding2', models.BinaryField(blank=True, null=True)),
                ('encoding3', models.BinaryField(blank=True, null=True)),
                ('photoUI', models.ImageField(blank=True, editable=False, max_length=300, upload_to='')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.classes')),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Pre-U', 'Pre-University')], max_length=14)),
                ('ay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.academic_year')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.division'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], default='A', max_length=1)),
                ('datetime', models.DateTimeField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.classes')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.students')),
            ],
        ),
    ]
