# Generated by Django 5.1 on 2024-12-03 09:14

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_students_photo1_alter_students_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='grade',
            field=models.CharField(choices=[('P1A', 'Primary 1A'), ('P1B', 'Primary 1B'), ('P2A', 'Primary 2A'), ('P2B', 'Primary 2B'), ('P3A', 'Primary 3A'), ('P3B', 'Primary 3B'), ('P4A', 'Primary 4A'), ('P4B', 'Primary 4B'), ('P5A', 'Primary 5A'), ('P5B', 'Primary 5B'), ('P6A', 'Primary 6A'), ('P6B', 'Primary 6B'), ('P7A', 'Primary 7A'), ('P7B', 'Primary 7B'), ('P8A', 'Primary 8A'), ('P8B', 'Primary 8B'), ('S9', 'Secondary 9'), ('S10', 'Secondary 10'), ('PU11', 'Pre-U 11'), ('PU12', 'Pre-U 12')], max_length=4),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo1',
            field=models.ImageField(max_length=300, upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo2',
            field=models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo3',
            field=models.ImageField(blank=True, max_length=300, upload_to=webapp.models.Rename.save),
        ),
    ]
